export const ADD_TO_CART ='ADD_TO_CART';
export const REMOVE_FROM_CART ='REMOVE_FROM_CART';
export const INCREASE_AMOUNT ='INCREASE_AMOUNT';
export const DECREASE_AMOUNT ='DECREASE_AMOUNT';
export const LOAD_CURRENT_ITEM ='LOAD_CURRENT_ITEM';
export const Get_TOTAL ='Get_TOTAL';